/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AwardBlock: typeof import('./src/components/pdf/block/AwardBlock.vue')['default']
    ButtonText: typeof import('./src/components/pdf/elem/ButtonText.vue')['default']
    CertificateBlock: typeof import('./src/components/pdf/block/CertificateBlock.vue')['default']
    CompetenceBlock: typeof import('./src/components/pdf/block/CompetenceBlock.vue')['default']
    ContentBlock: typeof import('./src/components/pdf/elem/ContentBlock.vue')['default']
    CVControl: typeof import('./src/components/cv/CVControl.vue')['default']
    CVPage: typeof import('./src/components/cv/CVPage.vue')['default']
    Divider: typeof import('./src/components/elem/Divider.vue')['default']
    DownloadButton: typeof import('./src/components/elem/button/DownloadButton.vue')['default']
    DynamicIcon: typeof import('./src/components/elem/DynamicIcon.vue')['default']
    EduBlock: typeof import('./src/components/pdf/block/EduBlock.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElText: typeof import('element-plus/es')['ElText']
    HeaderBlock: typeof import('./src/components/pdf/block/HeaderBlock.vue')['default']
    IconEpPrinter: typeof import('~icons/ep/printer')['default']
    IconEpShare: typeof import('~icons/ep/share')['default']
    IconPhDownloadSimpleBold: typeof import('~icons/ph/download-simple-bold')['default']
    IconPhFilePdf: typeof import('~icons/ph/file-pdf')['default']
    IconPhReadCvLogo: typeof import('~icons/ph/read-cv-logo')['default']
    LinkText: typeof import('./src/components/pdf/elem/LinkText.vue')['default']
    Paragraph: typeof import('./src/components/pdf/elem/Paragraph.vue')['default']
    PDFControl: typeof import('./src/components/pdf/PDFControl.vue')['default']
    PDFPage: typeof import('./src/components/pdf/PDFPage.vue')['default']
    PointText: typeof import('./src/components/pdf/elem/PointText.vue')['default']
    Popover: typeof import('./src/components/elem/Popover.vue')['default']
    PrintButton: typeof import('./src/components/elem/button/PrintButton.vue')['default']
    ProjectBlock: typeof import('./src/components/pdf/block/ProjectBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./src/components/pdf/elem/Separator.vue')['default']
    ShareButton: typeof import('./src/components/elem/button/ShareButton.vue')['default']
    SiteFooter: typeof import('./src/components/site/SiteFooter.vue')['default']
    SiteHeader: typeof import('./src/components/site/SiteHeader.vue')['default']
    SiteNav: typeof import('./src/components/site/SiteNav.vue')['default']
    Text: typeof import('./src/components/pdf/elem/Text.vue')['default']
  }
}
