/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./src/components/elem/button/AddButton.vue')['default']
    ControlBar: typeof import('./src/components/elem/ControlBar.vue')['default']
    DeleteButton: typeof import('./src/components/elem/button/DeleteButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    Header: typeof import('./src/components/admin/Header.vue')['default']
    IconCarbonTcpIpService: typeof import('~icons/carbon/tcp-ip-service')['default']
    IconLogosArchlinux: typeof import('~icons/logos/archlinux')['default']
    IconMaterialSymbolsAddCircleOutline: typeof import('~icons/material-symbols/add-circle-outline')['default']
    IconMaterialSymbolsDeleteForever: typeof import('~icons/material-symbols/delete-forever')['default']
    IconMaterialSymbolsFramePersonRounded: typeof import('~icons/material-symbols/frame-person-rounded')['default']
    IconSkillIconsAndroidstudioLight: typeof import('~icons/skill-icons/androidstudio-light')['default']
    IconSkillIconsAppleLight: typeof import('~icons/skill-icons/apple-light')['default']
    IconSkillIconsWindowsLight: typeof import('~icons/skill-icons/windows-light')['default']
    LogTable: typeof import('./src/components/log/LogTable.vue')['default']
    Pagination: typeof import('./src/components/elem/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/admin/Sidebar.vue')['default']
    Switch: typeof import('./src/components/elem/Switch.vue')['default']
    TokenDialog: typeof import('./src/components/token/TokenDialog.vue')['default']
    TokenTable: typeof import('./src/components/token/TokenTable.vue')['default']
  }
}
